### ISSUE TITLE
ConfigProvider not work

### ISSUE THREAD

**Issue by Valtas** [nanxiaobei/antd-img-crop#272]
ConfigProvider not work

babel-plugin-import is not used, the FAQ item is not applicable

NextJS 13.4.9

**Comment by nonam4** [comment]
I'm using NextJS and dynamically importing `antd-img-crop` and ConfigProvider is not working too

**Comment by nanxiaobei** [comment]
Because Next.js uses its own internal build system, this lib cannot fully adapt its behavior. 

The reason why `ConfigProvider` does not work is because `antd` in your project is inconsistent with the `antd` from this lib. 

In the future, we will consider allowing `antd` components to be passed in from `props` to handle this situation.
