### ISSUE TITLE
Contain props not working in mobile

### ISSUE THREAD

**Issue by vitorcremonez** [nanxiaobei/antd-img-crop#30]
Working like a charm on desktop, but **contain** is not working on mobile devices.

```jsx
<ImgCrop width={350} height={200} contain={true}>
          <Upload
            action="https://www.、/v2/5cc8019d300000980a055e76"
            listType="picture-card"
            fileList={fileList}
            onPreview={this.onPreview}
            onChange={this.onChange}
          >
            {fileList.length < 3 && "+ Upload"}
          </Upload>
</ImgCrop>
<Modal visible={previewShow} onCancel={this.onCancel} footer={null}>
<img src={previewSrc} style={{ maxWidth: "100%" }} alt="preview" />
</Modal>
```

**Comment by nanxiaobei** [comment]
Hello, thank you for your feedback~

Because `antd` itself is designed for the middle platform of the PC end, the mobile end is not considered. Therefore, this component has not tested the mobile, and it should not be specially compatible with the mobile.

If there is any problem, it is suggested to fork the mobile terminal test and optimization by yourself. Thank you.
