### ISSUE TITLE
Image rotation

### ISSUE THREAD

**Issue by flavaud-traceone** [nanxiaobei/antd-img-crop#31]
Hello @nanxiaobei!

I would like to submit a feature idea: have you considered adding a rotation utility to your component? It already does a great job, but it would be amazing with that. If not, are you open to a pull request? We may be able to do that in our team.

Thanks,

**Comment by nanxiaobei** [comment]
Now I don't have time to add this feature. If you can provide a PR, it will be very nice~

**Comment by mirofte** [comment]
Hello @nanxiaobei ,
I managed to create the zoom and rotation functionalitites for the component, but unfortunatelly I cannot create a PR since I don't have permission for it.
![error](https://user-images.githubusercontent.com/29098434/78559025-547b3700-781c-11ea-92c4-bea9fd4e47f0.png)

Can you please help me with that?
Thanks.

**Comment by nanxiaobei** [comment]
I think maybe there's something wrong with your PR submission steps.

**Comment by mirofte** [comment]
Hey @nanxiaobei,
Do you think you can help me with an estimation for when or if  this feature will be published? 
Thanks

**Comment by nanxiaobei** [comment]
Hi, I've released this feature for `2.5.0`.

But I changed `rotation` to `rotate`, `rotationTitle` to `rotateLabel`.

And I removed the `zoom` feature.

Because the component has a `resize` prop now, and `zoom` overlaps with `resize`(although slightly different).

For the sake of component simplicity, I removed `zoom`.

**Comment by mirofte** [comment]
Hey, thank you very much for the update.
`Resize` prop is nice, but it's hard to use when you have a large image and you want to pick one place in this image for example and maybe `Zoom` feature will help the user.
What do you think?

**Comment by nanxiaobei** [comment]
Hello, I've upgraded `antd-img-crop` to `3.0` now. It has been refactored with lib `react-easy-crop`, and  props 'zoom' and 'rotate' can be used.
